language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
cache:
  directories:
    - node_modules/
install:
  - npm install
script:
  - npm test
deploy:
  provider: npm
  email: $EMAIL
  api_key: $API_KEY
  on:
    tags: true
